[project]
name = "finance-agent"
version = "0.1.0"
description = "A agent to facilitate querying and processing finance data."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "html5lib>=1.1",
    "ipykernel>=7.2.0",
    "jupyter>=1.1.1",
    "lxml>=6.1.1",
    "matplotlib>=3.10.9",
    "pandas<3.0.0",
    "pandas-datareader>=0.10.0",
    "plotly>=6.8.0",
    "twstock>=1.5.1",
    "yfinance>=1.3.0",
]

[dependency-groups]
dev = [
    "pre-commit>=4.6.0",
]
